// Generated by CoffeeScript 1.9.3
(function() {
  var Ajax, Alert, clickcard, divbuttom, divtop, loadPhoto, log, root, scroll_to_load,
    slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.run = function() {
    return log("ajax.run");
  };

  log = function() {
    var i, k, len, results;
    results = [];
    for (k = 0, len = arguments.length; k < len; k++) {
      i = arguments[k];
      results.push(console.log(i));
    }
    return results;
  };

  Alert = function() {
    var arg;
    arg = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return alert(arg.join(''));
  };

  Ajax = function(filename) {
    var ajaxloader;
    log("ajax()");
    ajaxloader = new XMLHttpRequest();
    ajaxloader.open("GET", "Ajax/photos.json", true);
    ajaxloader.onreadystatechange = function() {
      if (ajaxloader.readyState === 4 && ajaxloader.status === 200) {
        root.re = JSON.parse(ajaxloader.responseText);
        loadPhoto();
        loadPhoto();
        loadPhoto();
        log("$(window).scrollTop():" + $(window).scrollTop());
        log("$(window).height():" + $(window).height());
        log("$(document).height():" + $(document).height());
        if ($(window).height() === $(document).height()) {
          log("load to fill the screen");
          return loadPhoto();
        }
      }
    };
    return ajaxloader.send();
  };

  loadPhoto = function() {
    var col, colAppendPhoto, k, len, loadAddiction, loaded, onload, ref;
    colAppendPhoto = function(col) {
      var card, cardcontent, content, img, imgsrc;
      imgsrc = re[id]['tumb'];
      cardcontent = "";
      img = $(document.createElement('div')).addClass('image').append($('<img />').attr('src', imgsrc)).attr('alt', 'id');
      if (cardcontent === !"") {
        content = $(document.createElement('div')).addClass('cardcontent').append($('<p />')).append(cardcontent);
      } else {
        content = null;
      }
      card = $(document.createElement('div')).addClass('card').append(img).append(content).attr('id', 'img_' + id).bind("click", clickcard);
      card.css("display", "none");
      card.appendTo(col);
      return id += 1;
    };
    loadAddiction = function() {
      var Ncol, buttom_of_short, i, j, k, l, lastCards, loadI, ref, ref1, results, top_of_long;
      Ncol = $('.column').length;
      lastCards = $('.column .card:last-child');
      if (lastCards === []) {
        return;
      }
      results = [];
      for (i = k = 0, ref = Ncol - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
        loadI = false;
        for (j = l = 0, ref1 = Ncol - 1; 0 <= ref1 ? l <= ref1 : l >= ref1; j = 0 <= ref1 ? ++l : --l) {
          if (i !== j) {
            buttom_of_short = divbuttom(lastCards[i]);
            top_of_long = divtop(lastCards[j]);
            if (divbuttom(lastCards[i]) < divtop(lastCards[j])) {
              loadI = true;
            }
          }
        }
        if (loadI) {
          results.push(colAppendPhoto(lastCards[i].parentNode));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };
    onload = function() {
      log("onload");
      $('body').addClass("loading");
      return log("onload done");
    };
    loaded = function() {
      log("loaded");
      $('body').removeClass("loading");
      $('.card').css("display", "inline-block");
      loadAddiction();
      return log("loaded done");
    };
    onload();
    log("append columns");
    ref = $('.column');
    for (k = 0, len = ref.length; k < len; k++) {
      col = ref[k];
      colAppendPhoto(col);
    }
    $('.columns').attr('onload', loaded);
    return log("append columns Done");
  };

  clickcard = function() {
    log("clickcard");
    return log(this);
  };

  scroll_to_load = function() {
    if ($(window).scrollTop() + $(window).height() > $(document).height() - 5) {
      return loadPhoto();
    }
  };

  divbuttom = function(div) {
    if (div === void 0) {
      return 100;
    } else {
      return $(div).position().top + $(div).height();
    }
  };

  divtop = function(div) {
    if (div === void 0) {
      return 0;
    } else {
      return $(div).position().top;
    }
  };

  window.id = 0;

  window.onkeydown = function() {
    log("onkeydown");
    return loadPhoto();
  };

  window.onresize = function() {
    return log("onresize");
  };

  window.onload = function() {
    return Ajax("Ajax/photos.json");
  };

  window.onscroll = function() {
    return scroll_to_load();
  };

}).call(this);
