// Generated by CoffeeScript 1.9.3
(function() {
  var Ajax, Alert, clickcard, divbuttom, divtop, loadPhoto, log, root, scroll_to_load,
    slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.run = function() {
    return log("ajax.run");
  };

  log = function() {
    var i, k, len, results;
    results = [];
    for (k = 0, len = arguments.length; k < len; k++) {
      i = arguments[k];
      results.push(console.log(i));
    }
    return results;
  };

  Alert = function() {
    var arg;
    arg = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return alert(arg.join(''));
  };

  Ajax = function(filename) {
    var ajaxloader;
    log("ajax()");
    ajaxloader = new XMLHttpRequest();
    ajaxloader.open("GET", "Ajax/photos.json", true);
    ajaxloader.onreadystatechange = function() {
      if (ajaxloader.readyState === 4 && ajaxloader.status === 200) {
        root.re = JSON.parse(ajaxloader.responseText);
        loadPhoto();
        loadPhoto();
        loadPhoto();
        log("$(window).scrollTop():" + $(window).scrollTop());
        log("$(window).height():" + $(window).height());
        log("$(document).height():" + $(document).height());
        if ($(window).height() === $(document).height()) {
          log("load to fill the screen");
          loadPhoto();
          return sleep;
        }
      }
    };
    return ajaxloader.send();
  };

  loadPhoto = function() {
    var Ncol, buttom_of_short, col, colAppendPhoto, i, j, k, l, lastCards, len, loadI, m, ref, ref1, ref2, results, top_of_long;
    Ncol = $('.column').length;
    colAppendPhoto = function(col) {
      var card, cardcontent, content, img, imgsrc;
      imgsrc = re[id]['tumb'];
      cardcontent = "";
      img = $(document.createElement('div')).addClass('image').append($('<img />').attr('src', imgsrc));
      if (cardcontent === !"") {
        content = $(document.createElement('div')).addClass('cardcontent').append($('<p />')).append(cardcontent);
      } else {
        content = null;
      }
      card = $(document.createElement('div')).addClass('card').append(img).append(content).attr('id', 'img_' + id).bind("click", clickcard);
      card.appendTo(col);
      return id += 1;
    };
    ref = $('.column');
    for (k = 0, len = ref.length; k < len; k++) {
      col = ref[k];
      colAppendPhoto(col);
    }
    lastCards = $('.column .card:last-child');
    results = [];
    for (i = l = 0, ref1 = Ncol - 1; 0 <= ref1 ? l <= ref1 : l >= ref1; i = 0 <= ref1 ? ++l : --l) {
      loadI = false;
      for (j = m = 0, ref2 = Ncol - 1; 0 <= ref2 ? m <= ref2 : m >= ref2; j = 0 <= ref2 ? ++m : --m) {
        if (i !== j) {
          buttom_of_short = divbuttom(lastCards[i]);
          top_of_long = divtop(lastCards[j]);
          if (divbuttom(lastCards[i]) <= divtop(lastCards[j])) {
            loadI = true;
          }
        }
      }
      if (loadI) {
        results.push(colAppendPhoto(lastCards[i].parentNode));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  clickcard = function() {
    log("clickcard");
    return log(this);
  };

  scroll_to_load = function() {
    if ($(window).scrollTop() + $(window).height() > $(document).height() - 50) {
      return loadPhoto();
    }
  };

  divbuttom = function(div) {
    return $(div).position().top + $(div).height();
  };

  divtop = function(div) {
    return $(div).position().top;
  };

  window.id = 0;

  window.onkeydown = function() {
    log("onkeydown");
    return loadPhoto();
  };

  window.onresize = function() {
    return log("onresize");
  };

  window.onload = function() {
    return Ajax("Ajax/photos.json");
  };

  window.onscroll = function() {
    return scroll_to_load();
  };

}).call(this);
